[PHP]
extension_dir="ext"
extension=pdo_mysql
extension=mysqli
extension=gd
extension=mbstring
extension=fileinfo
extension=curl
extension=openssl
extension=zip
extension=intl
memory_limit=256M
upload_max_filesize=15M
post_max_size=28M
max_file_uploads=20
date.timezone=Europe/Prague
display_errors=Off
log_errors=On
