<?php namespace ProcessWire;
$s=Craft::settings();$hero=Craft::page('hero');$about=Craft::page('o-nas');$advice=Craft::page('poradenstvi');
$nav=[];if(Craft::data($about)['enabled'])$nav['o-nas']='O nás';if($s['services_enabled'])$nav['sluzby']='Naše služby';if(Craft::data($advice)['enabled'])$nav['poradenstvi']='Poradenství';if($s['references_enabled'])$nav['realizace']='Realizace';$nav['kontakt']='Kontakt';
$phone=preg_replace('/[^+0-9]/','',$s['phone']);$logo=Craft::page('nastaveni')->craft_images->first();
$brand=Craft::branding($s,(bool)$logo);
$title=$isPrivacy?'Ochrana osobních údajů | '.$s['company']:$s['seo_title'];$canonical=rtrim($config->craft['baseUrl'],'/').($isPrivacy?'/ochrana-osobnich-udaju/':'/');$og=Craft::image($hero,1200);$e=fn($v)=>Craft::e($v);
header('X-Content-Type-Options: nosniff');header('Referrer-Policy: strict-origin-when-cross-origin');header('Cache-Control: no-store');
?><!doctype html>
<html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $e($title) ?></title><meta name="description" content="<?= $e($s['seo_description']) ?>"><link rel="canonical" href="<?= $e($canonical) ?>"><meta property="og:type" content="website"><meta property="og:title" content="<?= $e($title) ?>"><meta property="og:description" content="<?= $e($s['seo_description']) ?>"><meta property="og:url" content="<?= $e($canonical) ?>"><meta property="og:image" content="<?= $e(rtrim($config->craft['baseUrl'],'/').$og['url']) ?>"><link rel="icon" type="image/svg+xml" href="/site/templates/assets/favicon.svg"><link rel="stylesheet" href="/wire/templates-admin/styles/font-awesome/css/font-awesome.min.css"><link rel="stylesheet" href="/site/templates/assets/site.css"><script src="/site/templates/assets/site.js" defer></script></head>
<body><a class="skip-link" href="#main">Přejít na obsah</a><header class="site-header" id="header"><div class="wrap header-inner"><?php if(($logo && $brand['brand_show_image']) || $brand['brand_show_text']):?><a class="brand brand-font-<?= $e($brand['brand_font']) ?>" href="/" aria-label="<?= $e($s['company']) ?> – úvod"><?php if($logo && $brand['brand_show_image']):?><img src="<?= $e($logo->height(56)->url) ?>" alt="<?= $e($s['company']) ?>"><?php endif;?><?php if($brand['brand_show_text']):?><span class="brand-copy"><?= $e($brand['brand_text']) ?><?php if($brand['brand_tagline']!==''):?><small><?= $e($brand['brand_tagline']) ?></small><?php endif;?></span><?php endif;?></a><?php endif;?><nav class="desktop-nav" aria-label="Hlavní navigace"><?php foreach($nav as $id=>$label):?><a href="/#<?= $id ?>"><?= $label ?></a><?php endforeach;?></nav><a class="header-quote button button-small" href="/#kontakt">Nezávazná poptávka <span aria-hidden="true">↗</span></a><a class="header-phone" href="tel:<?= $e($phone) ?>" aria-label="Zavolat <?= $e($s['phone']) ?>"><svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M5 3h4l2 5-3 2c1 3 3 5 6 6l2-3 5 2v4c0 2-2 2-3 2C9 20 3 14 3 6c0-2 0-3 2-3Z"/></svg><span><?= $e($s['phone']) ?></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-nav" aria-label="Otevřít menu"><span></span><span></span></button></div><nav id="mobile-nav" class="mobile-nav" aria-label="Mobilní navigace" hidden><?php foreach($nav as $id=>$label):?><a href="/#<?= $id ?>"><?= $label ?></a><?php endforeach;?></nav></header>
