<?php namespace ProcessWire;
require_once __DIR__.'/lib/Intake.php';$s=Craft::settings();$errors=[];$values=$_POST;$success=false;
if($_SERVER['REQUEST_METHOD']==='POST'){$errors=Intake::submit($s);if(!$errors){$session->craftSuccess=true;$session->craftLastToken=$_POST['submission_token'];$session->craftToken=null;$session->redirect('/#kontakt',303);}}
if($session->craftSuccess){$success=true;$session->remove('craftSuccess');}
if(!$session->craftToken){$session->craftToken=bin2hex(random_bytes(32));$session->craftStarted=time();}
if($_SERVER['REQUEST_METHOD']==='GET')Craft::countView();
$isPrivacy=false;require __DIR__.'/partials/header.php';
$h=Craft::data($hero);$hi=Craft::image($hero,1800);$a=Craft::data($about);$ai=Craft::image($about,1000);$ad=Craft::data($advice);$adi=Craft::image($advice,1000);
?>
<main id="main"><section class="hero" aria-labelledby="hero-title"><img class="hero-image" src="<?= $e($hi['url']) ?>" srcset="<?= $e($hi['srcset']) ?>" sizes="100vw" alt="<?= $e($hi['alt']) ?>" fetchpriority="high"><div class="hero-shade"></div><div class="wrap hero-content"><?= Craft::sectionLabel('hero',$h,'eyebrow','eyebrow light') ?><h1 id="hero-title"><?= $e($h['heading']) ?></h1><div class="hero-tagline rich-text"><?= Craft::body($h) ?></div><a class="button" href="#kontakt">Nezávazná poptávka <span aria-hidden="true">↗</span></a><a class="hero-more" href="#<?= isset($nav['o-nas'])?'o-nas':'kontakt' ?>">Poznejte naši práci <span aria-hidden="true">↓</span></a></div></section>
<?php require __DIR__.'/partials/trust.php';?>
<?php if($a['enabled']):?><section id="o-nas" class="section wrap split about"><div class="section-copy"><?= Craft::sectionLabel('o-nas',$a,'eyebrow','eyebrow') ?><h2><?= $e($a['heading']) ?></h2></div><div class="section-image"><img src="<?= $e($ai['url']) ?>" srcset="<?= $e($ai['srcset']) ?>" sizes="(max-width:800px) 90vw,45vw" loading="lazy" alt="<?= $e($ai['alt']) ?>"><span class="image-corner" aria-hidden="true"></span></div><div class="section-body"><div class="rich-text"><?= Craft::body($a) ?></div><a class="text-link" href="#kontakt">Pojďme se domluvit <span aria-hidden="true">↗</span></a></div></section><?php endif;?>
<?php if($s['services_enabled']):?><section id="sluzby" class="section services-section"><div class="wrap"><div class="section-heading"><div><?= Craft::sectionLabel('services',$s,'eyebrow','eyebrow') ?><h2>Od nápadu k poctivému výsledku.</h2></div><?= Craft::sectionLabel('services',$s,'intro') ?></div><div class="services-grid">
<?php foreach(Craft::items('craft_service') as $i=>$item):$d=Craft::data($item);if(!$d['enabled'])continue;$im=Craft::image($item,800);?><article class="service-card"><div class="card-image"><img src="<?= $e($im['url']) ?>" srcset="<?= $e($im['srcset']) ?>" sizes="(max-width:600px) 90vw,(max-width:1000px) 45vw,30vw" loading="lazy" alt="<?= $e($im['alt']) ?>"><span><?= str_pad((string)($i+1),2,'0',STR_PAD_LEFT) ?></span></div><div class="card-body"><h3><?= $e($item->title) ?></h3><div class="rich-text"><?= Craft::body($d) ?></div></div></article><?php endforeach;?></div></div></section><?php endif;?>
<?php if($ad['enabled']):?><section id="poradenstvi" class="section wrap split advice"><div class="section-copy"><?= Craft::sectionLabel('poradenstvi',$ad,'eyebrow','eyebrow') ?><h2><?= $e($ad['heading']) ?></h2></div><div class="section-image"><img src="<?= $e($adi['url']) ?>" srcset="<?= $e($adi['srcset']) ?>" sizes="(max-width:800px) 90vw,45vw" loading="lazy" alt="<?= $e($adi['alt']) ?>"></div><div class="section-body"><div class="rich-text"><?= Craft::body($ad) ?></div><a class="button button-dark" href="#kontakt">Probereme váš projekt <span aria-hidden="true">↗</span></a></div></section><?php endif;?>
<?php $gallery=[];if($s['references_enabled']):?><section id="realizace" class="section reference-section"><div class="wrap"><div class="section-heading"><div><?= Craft::sectionLabel('references',$s,'eyebrow','eyebrow') ?><h2>Reference</h2></div><?= Craft::sectionLabel('references',$s,'intro') ?></div><div class="references-grid">
<?php foreach(Craft::items('craft_reference') as $item):$d=Craft::data($item);if(!$d['enabled'])continue;$im=Craft::image($item,1000);$photos=[];foreach($item->craft_images as $photo)$photos[]=['url'=>$photo->width(min(1600,$photo->width))->url,'alt'=>$photo->description?:$item->title];if(!$photos)$photos[]=['url'=>$im['url'],'alt'=>$im['alt']];$gallery[$item->id]=['title'=>$item->title,'location'=>$d['location'],'description'=>Craft::body($d),'photos'=>$photos];?><article class="reference-card"><a href="<?= $e($im['url']) ?>" class="gallery-open" data-project="<?= $item->id ?>" aria-label="Otevřít fotografie: <?= $e($item->title) ?>"><div class="reference-image"><img src="<?= $e($im['url']) ?>" srcset="<?= $e($im['srcset']) ?>" sizes="(max-width:700px) 90vw,30vw" loading="lazy" alt="<?= $e($im['alt']) ?>"><span class="expand" aria-hidden="true">↗</span><span class="photo-count"><?= count($photos) ?> fotografie</span></div><div class="reference-title"><h3><?= $e($item->title) ?></h3><p><?= $e($d['location']) ?></p></div></a></article><?php endforeach;?></div></div></section><?php endif;?>
<section id="kontakt" class="section contact-section"><div class="wrap contact-grid"><div class="contact-info"><?= Craft::sectionLabel('contact',$s,'eyebrow','eyebrow light') ?><h2>Dobrá práce začíná<br>dobrou domluvou.</h2><?= Craft::sectionLabel('contact',$s,'intro') ?><a class="contact-phone" href="tel:<?= $e($phone) ?>"><?= $e($s['phone']) ?> <span aria-hidden="true">↗</span></a><a class="contact-email" href="mailto:<?= $e($s['email']) ?>"><?= $e($s['email']) ?></a><div class="contact-details"><strong><?= $e($s['company']) ?></strong><?php if($s['show_address']):?><p><?= nl2br($e($s['address'])) ?></p><?php endif;?><p class="billing"><?= nl2br($e($s['billing'])) ?></p></div></div><div class="contact-form"><h3><?= $e($s['contact_heading']) ?></h3><p><?= $e($s['contact_text']) ?></p>
<?php require __DIR__.'/partials/form.php';?></div><?php if($s['show_map']&&preg_match('~^https://(?:frame\.)?(?:mapy\.com|mapy\.cz)/~',$s['map_url'])):?><div class="map"><iframe src="<?= $e($s['map_url']) ?>" title="Mapa umístění firmy" loading="eager" referrerpolicy="strict-origin-when-cross-origin"></iframe><a href="<?= $e($s['map_url']) ?>" target="_blank" rel="noopener">Otevřít v Mapy.com ↗</a></div><?php endif;?></div></section></main>
<dialog id="gallery" aria-labelledby="gallery-title"><div class="gallery-toolbar"><span id="gallery-counter"></span><button type="button" class="gallery-close" aria-label="Zavřít galerii">×</button></div><div class="gallery-stage"><button type="button" class="gallery-prev" aria-label="Předchozí fotografie">←</button><img id="gallery-image" alt=""><button type="button" class="gallery-next" aria-label="Další fotografie">→</button></div><div class="gallery-caption"><p id="gallery-location" class="eyebrow"></p><h2 id="gallery-title"></h2><div id="gallery-description" class="rich-text"></div></div></dialog><script type="application/json" id="gallery-data"><?= json_encode($gallery,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE) ?></script><?php require __DIR__.'/partials/footer.php';?>

